In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
data = pd.read_csv("/content/test_energy_data (1).csv")

In [41]:
data.head()

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week,Energy Consumption
0,Residential,24563,15,4,28.52,Weekday,2865.57
1,Commercial,27583,56,23,23.07,Weekend,4283.80
2,Commercial,45313,4,44,33.56,Weekday,5067.83
3,Residential,41625,84,17,27.39,Weekend,4624.30
4,Residential,36720,58,47,17.08,Weekday,4820.59

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Building Type        100 non-null    object
 1   Square Footage       100 non-null    int64
 2   Number of Occupants  100 non-null    int64
 3   Appliances Used      100 non-null    int64
 4   Average Temperature  100 non-null    float64
 5   Day of Week          100 non-null    object
 6   Energy Consumption   100 non-null    float64
dtypes: float64(2), int64(3), object(2)
memory usage: 5.6+ KB

In [43]:
data.describe()

,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Energy Consumption
count,100.000000,100.000000,100.000000,100.000000,100.00000
mean,25881.920000,47.230000,26.970000,22.043300,4187.57830
std,13711.075264,29.905526,14.237846,6.957951,832.55985
min,1161.000000,2.000000,1.000000,10.400000,2351.97000
25%,14161.000000,21.000000,16.750000,15.682500,3621.92500
50%,27582.500000,47.000000,27.500000,21.970000,4249.39000
75%,38109.500000,73.000000,39.250000,27.492500,4797.17500
max,49354.000000,99.000000,49.000000,34.710000,6042.56000

In [44]:
data.isnull().sum()

Building Type          0
Square Footage         0
Number of Occupants    0
Appliances Used        0
Average Temperature    0
Day of Week            0
Energy Consumption     0
dtype: int64

In [45]:
mean_val =  data['Energy Consumption'].mean()
median_val = data['Energy Consumption'].median()
mode_val = data['Energy Consumption'].mode()[0]

print("Mean:", mean_val)
print("Median:", median_val)
print("Mode:", mode_val)

Mean: 4187.5783
Median: 4249.389999999999
Mode: 2351.97

In [46]:
print(data['Building Type'].value_counts())
print('=========================================')
print(data['Day of Week'].value_counts())

Building Type
Residential    40
Industrial     34
Commercial     26
Name: count, dtype: int64
=========================================
Day of Week
Weekend    56
Weekday    44
Name: count, dtype: int64

In [48]:
data = pd.get_dummies(data, columns=['Building Type', 'Day of Week'], drop_first=True, dtype=int)
data.head()

,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Energy Consumption,Building Type_Industrial,Building Type_Residential,Day of Week_Weekend
0,24563,15,4,28.52,2865.57,0,1,0
1,27583,56,23,23.07,4283.80,0,0,1
2,45313,4,44,33.56,5067.83,0,0,0
3,41625,84,17,27.39,4624.30,0,1,1
4,36720,58,47,17.08,4820.59,0,1,0

In [50]:
x = data.drop('Energy Consumption', axis=1)
y = data['Energy Consumption']

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(80, 7)
(20, 7)
(80,)
(20,)

In [53]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [54]:
y_pred = model.predict(X_test)

In [55]:
from sklearn import metrics
r2_score = model.score(X_test, y_test)
mse = metrics.root_mean_squared_error(y_test, y_pred)

print(f'R-squared: {r2_score}')
print(f'Root Mean Squared Error: {mse}')

R-squared: 0.9999999996232116
Root Mean Squared Error: 0.015852663332926675

In [58]:
import pickle

# Save the preprocessed data (including encoded 'Building Type' and 'Day of Week')
with open('preprocessed_energy_data.pkl', 'wb') as f:
    pickle.dump(data, f)
print("Preprocessed data saved to 'preprocessed_energy_data.pkl'")


# Save the trained model
with open('linear_regression_model.pkl', 'wb') as f:
    pickle.dump(model, f)
print("Trained Linear Regression model saved to 'linear_regression_model.pkl'")

Preprocessed data saved to 'preprocessed_energy_data.pkl'
Trained Linear Regression model saved to 'linear_regression_model.pkl'